// <auto-generated />
using System;
using FiapCloudGames.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiapCloudGames.Infra.Data.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20260412165334_AlterarTamanhoNomeJogo")]
    partial class AlterarTamanhoNomeJogo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FiapCloudGames.Domain.Entities.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("jogo_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("jogo_datahora")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("jogo_nome");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("jogo_situacao");

                    b.HasKey("Id");

                    b.ToTable("tbl_jogo", (string)null);
                });

            modelBuilder.Entity("FiapCloudGames.Domain.Entities.Perfil", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint(2)")
                        .HasColumnName("perfil_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("perfil_datahora")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("perfil_nome");

                    b.HasKey("Id");

                    b.ToTable("tbl_perfil", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            DataHora = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Administrador"
                        },
                        new
                        {
                            Id = (short)2,
                            DataHora = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Usuário"
                        });
                });

            modelBuilder.Entity("FiapCloudGames.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("usuario_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("usuario_datahora")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("usuario_email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("usuario_nome");

                    b.Property<short>("PerfilId")
                        .HasColumnType("smallint(2)")
                        .HasColumnName("perfil_id");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("usuario_senha");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("usuario_situacao");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("tbl_usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataHora = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@fiapcloud.com.br",
                            Nome = "Admin",
                            PerfilId = (short)1,
                            Senha = "$2a$12$svXQ729NloenitUUO6SVVuQ/dozPgz43tm/rOrMIDppxix0YFtYJW",
                            Situacao = "\0"
                        });
                });

            modelBuilder.Entity("FiapCloudGames.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("FiapCloudGames.Domain.Entities.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });
#pragma warning restore 612, 618
        }
    }
}
