// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FiapCloudGames.Tests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AdicionarUsuarioFeature : object, Xunit.IClassFixture<AdicionarUsuarioFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AdicionarUsuario.feature"
#line hidden
        
        public AdicionarUsuarioFeature(AdicionarUsuarioFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-br"), "Features", "Adicionar Usuário", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 4
#line hidden
#line 5
    await testRunner.GivenAsync("que eu estou autenticado como \"Administrador\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Adicionar novo usuário com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Adicionar Usuário")]
        [Xunit.TraitAttribute("Description", "Adicionar novo usuário com sucesso")]
        public async System.Threading.Tasks.Task AdicionarNovoUsuarioComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Adicionar novo usuário com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Senha",
                            "PerfilId"});
                table3.AddRow(new string[] {
                            "Fulano de Tal",
                            "fulano@fiap.com",
                            "Teste@123",
                            "1"});
#line 8
    await testRunner.GivenAsync("que eu preencho os dados do novo usuário:", ((string)(null)), table3, "Dado ");
#line hidden
#line 11
    await testRunner.WhenAsync("eu solicitar a adição do usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 12
    await testRunner.ThenAsync("o sistema deve retornar o status 201 Created", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Erro ao tentar adicionar usuário com e-mail já existente")]
        [Xunit.TraitAttribute("FeatureTitle", "Adicionar Usuário")]
        [Xunit.TraitAttribute("Description", "Erro ao tentar adicionar usuário com e-mail já existente")]
        public async System.Threading.Tasks.Task ErroAoTentarAdicionarUsuarioComE_MailJaExistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Erro ao tentar adicionar usuário com e-mail já existente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
#line 15
    await testRunner.GivenAsync("que já existe um usuário cadastrado com o e-mail \"duplicado@fiap.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 16
    await testRunner.AndAsync("que eu preencho os dados do novo usuário com o e-mail \"duplicado@fiap.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 17
    await testRunner.WhenAsync("eu solicitar a adição do usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 18
    await testRunner.ThenAsync("o sistema deve retornar o status 409 Conflict", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Erro ao tentar adicionar usuário com dados inválidos")]
        [Xunit.TraitAttribute("FeatureTitle", "Adicionar Usuário")]
        [Xunit.TraitAttribute("Description", "Erro ao tentar adicionar usuário com dados inválidos")]
        [Xunit.InlineDataAttribute("", "teste@gmail.com", "Senha@123", "1", "Insira o nome do usuário.", new string[0])]
        [Xunit.InlineDataAttribute("Luigi", "email_invalido", "Senha@123", "1", "O e-mail inserido é inválido.", new string[0])]
        [Xunit.InlineDataAttribute("Peach", "peach@gmail.com", "123", "1", "A senha precisa ter no mínimo 8 dígitos, contendo números, letras e caracteres es" +
            "peciais.", new string[0])]
        [Xunit.InlineDataAttribute("Yoshi", "yoshi@gmail.com", "Senha@123", "null", "Insira o ID do perfil do usuário.", new string[0])]
        public async System.Threading.Tasks.Task ErroAoTentarAdicionarUsuarioComDadosInvalidos(string nome, string email, string senha, string perfilId, string mensagem, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("nome", nome);
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("senha", senha);
            argumentsOfScenario.Add("perfilId", perfilId);
            argumentsOfScenario.Add("mensagem", mensagem);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Erro ao tentar adicionar usuário com dados inválidos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Nome",
                            "Email",
                            "Senha",
                            "PerfilId"});
                table4.AddRow(new string[] {
                            string.Format("{0}", nome),
                            string.Format("{0}", email),
                            string.Format("{0}", senha),
                            string.Format("{0}", perfilId)});
#line 21
    await testRunner.GivenAsync("que eu tento adicionar um usuário com os seguintes dados:", ((string)(null)), table4, "Dado ");
#line hidden
#line 24
    await testRunner.WhenAsync("eu solicitar a adição do usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 25
    await testRunner.ThenAsync("o sistema deve retornar o status 400 BadRequest", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 26
    await testRunner.AndAsync(string.Format("a resposta deve conter a mensagem de erro \"{0}\"", mensagem), ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await AdicionarUsuarioFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await AdicionarUsuarioFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
