<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<UserSecretsId>5dd5906c-0b97-4f70-9930-83f6138b80cc</UserSecretsId>
		<Reqnroll_EnableCodeBehindGenerator>true</Reqnroll_EnableCodeBehindGenerator>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.3.9" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.25" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="Reqnroll.Microsoft.Extensions.DependencyInjection" Version="2.0.1" />
		<PackageReference Include="Reqnroll.Tools.MsBuild.Generation" Version="2.0.1" />
		<PackageReference Include="Reqnroll.xUnit" Version="2.0.1" />
		<PackageReference Include="xunit" Version="2.5.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FiapCloudGames.Api\FiapCloudGames.Api.csproj" />
		<ProjectReference Include="..\FiapCloudGames.Domain\FiapCloudGames.Domain.csproj" />
		<ProjectReference Include="..\FiapCloudGames.Infra.Data\FiapCloudGames.Infra.Data.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

</Project>
